# Generated by Django 2.1.7 on 2019-04-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('header', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('valid_until', models.DateTimeField()),
                ('content_file',
                 models.ManyToManyField(blank=True, to='backend.File')),
                ('group_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='backend.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('header', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('content_file',
                 models.ManyToManyField(blank=True, to='backend.File')),
                ('group_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='backend.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('header', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('content_file',
                 models.ManyToManyField(blank=True, to='backend.File')),
                ('group_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='backend.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('patronymic_name',
                 models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telegram_account',
                 models.CharField(blank=True, max_length=255)),
                ('completed_homeworks',
                 models.ManyToManyField(to='backend.Homework')),
            ],
        ),
        migrations.CreateModel(
            name='StudentJar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='student_jars_created',
                                   to='backend.Student')),
                ('students', models.ManyToManyField(to='backend.Student')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='backend.Student'),
        ),
    ]
