# Generated by Django 2.1.7 on 2019-05-26 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='moderators',
            field=models.ManyToManyField(related_name='groups_moderated', to='backend.Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='student_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_created', to='backend.Student'),
        ),
    ]
