# Generated by Django 2.1.7 on 2019-04-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_student_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='created_at',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='homework',
            name='valid_until',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.BigIntegerField(),
        ),
    ]
