# Generated by Django 2.1.7 on 2019-05-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190526_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_token',
            field=models.CharField(db_index=True, default=None, max_length=256, null=True),
        ),
    ]
