# Generated by Django 2.1.7 on 2019-06-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190601_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentjar',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studentjar',
            name='students',
        ),
        migrations.DeleteModel(
            name='StudentJar',
        ),
    ]
