/**
 * AMI
 * fuck the cs hse
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HomeTask'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/HomeTask'));
  } else {
    // Browser globals (root is window)
    if (!root.Ami) {
      root.Ami = {};
    }
    root.Ami.DeadlinesApi = factory(root.Ami.ApiClient, root.Ami.HomeTask);
  }
}(this, function(ApiClient, HomeTask) {
  'use strict';

  /**
   * Deadlines service.
   * @module api/DeadlinesApi
   * @version 1.0.0
   */

  /**
   * Constructs a new DeadlinesApi. 
   * @alias module:api/DeadlinesApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the studentStudentIdDeadlinesGet operation.
     * @callback module:api/DeadlinesApi~studentStudentIdDeadlinesGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/HomeTask>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} studentId ID of student to return
     * @param {module:api/DeadlinesApi~studentStudentIdDeadlinesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/HomeTask>}
     */
    this.studentStudentIdDeadlinesGet = function(studentId, callback) {
      var postBody = null;

      // verify the required parameter 'studentId' is set
      if (studentId === undefined || studentId === null) {
        throw new Error("Missing the required parameter 'studentId' when calling studentStudentIdDeadlinesGet");
      }


      var pathParams = {
        'student_id': studentId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [HomeTask];

      return this.apiClient.callApi(
        '/student/{student_id}/deadlines', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
